on:
  pull_request:
    types:
      - closed
#    branches:
#      - master

jobs:
  sync_prs_from_community_to_enterprise:
    runs-on: ubuntu-latest
    name: Syncs merged PRs from Panther Community to Panther Enterprise
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Monitor PRs on Community & Create PRs on Enterprise
        uses: ./build/actions/pr_sync
        env:
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
        with:
          destRepo: 3nvi/panther
          ignoreLabel: enterprise-backport
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the output
        run: echo "${{ steps.sync_prs_from_community_to_enterprise.outputs.message }}"
